pipeline{

     environment {
          name = 'impweb'
          registry='nexus-dev.securegion.com'
          registryport='18079'
          registryurl=''
           }
     agent any

     stages {

          stage('Clone') {
           when { branch 'dev'}
               steps{
                    echo 'getting code...'+env.BRANCH_NAME
                    checkout scm
               }
          }


          stage('Install') {
           when { branch 'dev'}
               steps{
                    sh 'sh install.sh'
                  
               }
          }

           stage('Build') {
           when { branch 'dev'}
               steps{
                    sh 'sh build.sh'
               }
          }

          stage("Packaging"){
            when { branch 'dev'}
            steps{
                echo 'preparing docker'
                sh 'docker build -t ${name} .'
                sh 'docker tag ${name} ${registry}:${registryport}/${name}'
            }
          }

          stage("Push dev registry"){
            when {branch 'dev'}
            steps{
                  sh 'docker push ${registry}:${registryport}/${name} '
            }
          }

           stage("Install on dev"){
                when {branch 'dev'}
                steps{
                   sh 'ssh root@dev docker pull ${registry}:${registryport}/${name} '
                   sh 'ssh root@dev docker rm -f ${name} || true'
                   sh 'ssh root@dev docker run --name ${name} -d -p 5001:80 ${registry}:${registryport}/${name} '
                }
             }

	}
}
